### ISSUE TITLE
Floating point representation errors may cause incorrect codes

### ISSUE THREAD

**Issue by drinckes** [google/open-location-code#307]
How floating point numbers are represented in different languages can cause surprising results on common operations. If these occur, we could generate incorrect codes. A few cases have been identified where this happens.

This doesn't seem to occur when the latitude or longitude have four or more decimal places. Browser locations and GPS coordinates return more than this so it doesn't appear to affect codes generated using these as input.

One example is when either latitude or longitude is 35.6. This *should* be encoded as follows:

1. Add 90 to force it into a positive range giving 125.6
1. 20 (the place value for the first digit) goes into 125.6 six times, leaving 5.6 over and returning "**8**" (the digit with the value of 6)
1. 1 (the place value for the second digit) goes into 5.6 five times, leaving 0.6 over and returning "**7**" (the digit with the value of 5)
1. 0.05 goes into 0.6 twelve times, leaving 0 over, and returning the digit "**J**".
1. Further digits would be "2"s, since there is nothing left over.

If 35.6 was provided as latitude, it's code would look like "**8.7.J.2.+2.**" (where "."s are the longitude digits.) However many of the current implementations will return "**8.7.H.X.+X.**". (This is the OLC cell immediately to the north.)

This is due to how numbers are represented using mantissa and exponent. For example, in some languages 125.6 - 120 is 5.59999999999999000, not 5.6, and eventually the error becomes large enough to push the coordinate into the next OLC cell. (There's a good explanation of the problem [here](https://docs.python.org/3.1/faq/design.html#why-are-floating-point-calculations-so-inaccurate), and a much more technical explanation [here](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html)).

Similarly, 3.033 will be encoded incorrectly due to 0.0005 divided by 0.000125 being rounded to **3** instead of **4**.

I believe the solution is to use integer arithmetic to compute the codes. This is the approach taken by the new JS implementation in #305, and it was testing of this implementation that identified that it behaved differently to the other implementations. Initially I thought it was a bug - I just didn't realise it was a bug in everything else.

I suggest:
1. Adding a couple of test cases to identify implementations that are affected.
1. Submitting the JS implementation to confirm it fixes this issue.
1. Modifying affected implementations to use the integer arithmetic method.

This isn't good but I think that given the conditions that cause it are fairly unusual, that it's manageable and that it probably isn't affecting anyone in practice.

**Comment by zongweil** [comment]
This looks like the same issue that I ran across in the Java implementation (#217). From our internal discussion, we decided that we would live with the slight imprecision so that we would have consistency between all the implementations. 

Are you saying now that we should go the other way? Is there a more "correct" code to return in this edge case?

**Comment by drinckes** [comment]
We thought it was only the Java implementation. It turns out that AFAICT they're all wrong. Since they're not operating how described, I think they should be updated?

**Comment by zongweil** [comment]
I believe the Java implementation was behaving correctly before I made the change (floating point precision was correctly handled by BigDecimal). Looking back, instead of matching the Java implementation to the others, we should have matched the others to the Java implementation.

I think updating them makes sense if it leads to a more precise code returned. I'll revert the change I made to the Java library.

**Comment by zongweil** [comment]
Oops didn't mean to close this.

**Comment by fulldecent** [comment]
# Work plan

- [ ] Adding a couple of test cases to identify implementations that are affected.
- [ ] Submitting the JS implementation to confirm it fixes this issue.
- [ ] Modifying affected implementations to use the integer arithmetic method.

**Comment by fulldecent** [comment]
Recommended tag: <kbd>implementation</kbd> <kbd>testing</kbd>

**Comment by fulldecent** [comment]
@drinckes Thank you for the reference to #305 as a potential solution. There's a lot in that PR, could you please point to the relevant code or summarize here?

Personally I am considering to encode as:

```
function encode(double lat, double long)
    set latToEncode = floor( lat.plus(90).clamp(-90, 90) * 25_000_000 )
    set longToEncode = floor( long.mod(360) * 8_192_000 )

    ... then encode in bases(20, 20, 20, 20, 20, 4, 5, 4, 5, 4)
    ... and bases(20, 20, 20, 20, 20, 5, 4, 5, 4, 5)
```

I have not yet tested it to your test cases above. And I'm studying your other options. I am also considering to propose this as the reference implementation if it is correct.

**Comment by fulldecent** [comment]
This issue is partially fixed in https://github.com/google/open-location-code/pull/463

The Open Location Code API Specification includes notes about floating point errors and it includes a recommendation implementation that produces correct results.

It also references classes of floating point errors that are not discussed in this issue.

---

The above PR does NOT implement the required/recommended functionality. But because we also have https://github.com/google/open-location-code/pull/306, I recommend to close this issue as a (pre) duplicate of https://github.com/google/open-location-code/pull/306

**Comment by drinckes** [comment]
As pretty much all implementations are now integer based other than the initial conversion from floats, this seems to be resolved.
