### ISSUE TITLE
Use consistent naming in this repository -- plus codes or open location code

### ISSUE THREAD

**Issue by fulldecent** [google/open-location-code#431]
The README and FAQ here clarify:

- That "**plus codes**" (always lower case, similar to "postal codes") are the things that baseline humans and postpeople are going to use to find things on this big blue/green orb we live on; and
- That "**Open Location Code**" (always singular, always upper case, a proper noun) is the technology that developers will use to create the plus codes.

This messaging is frustrated by several inconsistencies in this repository.

# Work plan

- [ ] Change every reference to ["Open Location Codes"](https://github.com/google/open-location-code/search?q=%22open+location+codes%22)
  - These words literally mean "forks of the Open Location Code repository". Instead those should be referring to probably "plus codes" and or "Open Location Code".
- [ ] Rename all implementations to "Open Location Code".
  - Implementations here are named "PlusCodes" "Plus+Codes" "Plus Codes" and more. These violate the naming established above and contribute to confusion.
  - Every implementation Google publishes (i.e. in this repository) should be named just "Open Location Code". 
  - It is not established that "Open Location Code" is a name that is dedicated to the public domain. i.e. I'm not sure if it is appropriate for me to write an Open Location Code implementation and then name that implementation, for example, "Solidity Open Location Code". This could be a separate issue.
- [ ] Review every remaining mention of `/Open Location Codes?/i` and `/plus.{0,5}codes/I` in this repo to find stray word misusage.

# Work plan outside this project (e.g. advocacy)

- [ ] Reach out to every project/repository that is linked from this project, identify any word misusage, and recommend to fix it

**Comment by fulldecent** [comment]
Separately, this is mentioned in https://github.com/google/open-location-code/wiki/Naming-guidelines and that needs to be brought into one of the normative specifications

**Comment by fulldecent** [comment]
Recommended tags: <kbd>implementation</kbd> <kbd>specification</kbd> <kbd>documentation</kbd>

**Comment by fulldecent** [comment]
This is partially fixed at https://github.com/google/open-location-code/pull/463

The documentation is updated to make consistent and correct usage of Plus Code versus Open Location Code.

Implementations are not updated. I hope this PR can please be reviewed and merged before I consider the implementations.

**Comment by drinckes** [comment]
The naming guidelines document says that Plus Codes should be in title case. If other docs are inconsistent they should be brought into line with that before we change that definition.

**Comment by fulldecent** [comment]
Got it.

So we want to update https://github.com/google/open-location-code/pull/650 to use title case "Plus Codes" because of specification at https://github.com/google/open-location-code/blob/4d83aed0d78ce7904bb7de9241eaac5599d1a893/Documentation/Specification/Naming_Guidelines.md?plain=1#L11-L20
